linters-settings:
  lll:
    line-length: 320
  funlen:
    lines: 150
    statements: 90
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - paramTypeCombine
      - hugeParam
      - importShadow
  misspell:
    locale: US
  errcheck:
    check-blank: false
  golint:
    min-confidence: 1.0
run:
  tests: false
  deadline: 5m

linters:
  enable:
    - bodyclose
    - depguard
    #- dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
   # - interfacer
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    #- whitespace
service:
  golangci-lint-version: 1.18.x